Repository asdf-format/asdf, pull requests merged in 2018-10, with the labels that each got.

#549 Make sure extension metadata is written in all cases
  CHANGES.rst
  asdf/asdf.py
  asdf/tags/core/tests/test_history.py
Labels: bug

#553 Properly validate large numpy integer literals
  CHANGES.rst
  asdf/schema.py
  asdf/tests/test_schema.py
Labels: bug

#550 Add sanity check for extension override
  asdf/tests/test_asdftypes.py
Labels: no-changelog-entry-needed, testing

#560 Fix issue causing subclass to be serialized by wrong extension
  CHANGES.rst
  asdf/asdftypes.py
  asdf/extension.py
  asdf/tests/test_asdftypes.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_schema.py
Labels: bug

#562 Gracefully handle missing astropy in _open_impl
  CHANGES.rst
  asdf/asdf.py
Labels: bug

#568 Fix warning caused by potential comparison with NaN arrays
  asdf/block.py
  asdf/tests/test_low_level.py
Labels: bug, no-changelog-entry-needed

#569 Address warnings when using pytest 3.8
  .travis.yml
  appveyor.yml
  asdf/conftest.py
  asdf/tests/__init__.py
  asdf/tests/conftest.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_suite.py
  conftest.py
Labels: no-changelog-entry-needed, testing

#571 Allow tree to be created even when schema is missing
  CHANGES.rst
  asdf/schema.py
  asdf/tests/test_schema.py
Labels: bug

#572 Add test for serializing/deserializing type without schema
  asdf/tests/test_asdftypes.py
Labels: no-changelog-entry-needed, testing

#577 Fast finish Travis jobs
  .travis.yml
Labels: no-changelog-entry-needed, testing

#583 Add custom warning class for failure to convert into custom types
  CHANGES.rst
  asdf/exceptions.py
  asdf/tests/helpers.py
  asdf/tests/test_helpers.py
  asdf/yamlutil.py
Labels: enhancement, feature request

#579 Refactor, better mode handling, deprecate asdf.AsdfFile.open
  CHANGES.rst
  asdf/__init__.py
  asdf/asdf.py
  asdf/block.py
  asdf/commands/defragment.py
  asdf/commands/diff.py
  asdf/commands/exploded.py
  asdf/commands/tests/test_defragment.py
  asdf/commands/tests/test_to_yaml.py
  asdf/commands/to_yaml.py
  asdf/extern/atomicfile.py
  asdf/fits_embed.py
  asdf/generic_io.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_complex.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tags/wcs/tests/test_wcs.py
  asdf/tests/helpers.py
  asdf/tests/schema_tester.py
  asdf/tests/test_asdftypes.py
  asdf/tests/test_compression.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_low_level.py
  asdf/tests/test_reference.py
  asdf/tests/test_schema.py
  asdf/tests/test_stream.py
  asdf/tests/test_yaml.py
  docs/asdf/features.rst
  docs/sphinxext/example.py
Labels: bug, enhancement
