Repository asdf-format/asdf, pull requests merged in 2018-04, with the labels that each got.

#486 See if lz4 test failure on Windows has resolved itself
  asdf/commands/tests/test_defragment.py
Labels: no-changelog-entry-needed, testing

#487 Support clients who are still using the old history format
  asdf/asdf.py
Labels: no-changelog-entry-needed

#490 Make the build reproducible
  asdf/asdf.py
  docs/conf.py
Labels: no-changelog-entry-needed

#491 Add option to ignore missing extensions
  asdf/asdf.py
  asdf/fits_embed.py
  asdf/tags/core/tests/test_history.py
  asdf/tests/test_fits_embed.py
Labels: no-changelog-entry-needed

#492 Do not check extensions when forcing raw types
  asdf/asdf.py
Labels: bug, no-changelog-entry-needed

#460 Documentation overhaul for v2.0
  MANIFEST.in
  README.md
  README.rst
  asdf/__init__.py
  asdf/_internal_init.py
  asdf/asdf.py
  asdf/asdftypes.py
  asdf/extension.py
  asdf/extern/decorators.py
  asdf/tests/data/fraction-1.0.0.yaml
  asdf/tests/data/fractional_2d_coord-1.0.0.yaml
  asdf/tests/helpers.py
  asdf/util.py
  asdf/versioning.py
  asdf/yamlutil.py
  docs/asdf/arrays.rst
  docs/asdf/asdf_tool.rst
  docs/asdf/changes.rst
  docs/asdf/developer_api.rst
  docs/asdf/examples.rst
  docs/asdf/extensions.rst
  docs/asdf/features.rst
  docs/asdf/install.rst
  docs/asdf/overview.rst
  docs/asdf/user_api.rst
  docs/asdf/using_extensions.rst
  docs/conf.py
  docs/index.rst
  docs/sphinxext/example.py
  licenses/SUNPY_LICENSE.rst
  setup.cfg
  setup.py
Labels: no-changelog-entry-needed

#497 Make sure that the README renders properly on pypi
  .travis.yml
  README.rst
  setup_helpers.py
Labels: Docs, bug, no-changelog-entry-needed

#496 Documentation improvements based on feedback
  docs/_static/custom.css
  docs/asdf/extensions.rst
  docs/conf.py
  docs/index.rst
  docs/sphinxext/example.py
Labels: Docs, no-changelog-entry-needed
