Repository asdf-format/asdf, pull requests merged in 2018-08, with the labels that each got.

#527 Update tox.ini
  tox.ini
Labels: no-changelog-entry-needed

#529 Restrict jsonschema version to avoid using alpha release
  .travis.yml
  setup.py
Labels: no-changelog-entry-needed

#532 Add tests for validating nested arrays
  asdf/tests/test_schema.py
Labels: no-changelog-entry-needed, testing

#533 Ensure when closing, to explicitly close data blocks
  CHANGES.rst
  asdf/block.py
  asdf/tests/test_fits_embed.py
Labels: ready_for_final_review

#535 Add flake8 style checks to CI matrix
  .travis.yml
  asdf/asdf.py
  asdf/asdftypes.py
  asdf/commands/tests/__init__.py
  asdf/reference.py
  asdf/tagged.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/wcs/tests/__init__.py
  asdf/tests/schema_tester.py
  asdf/tests/test_compression.py
  asdf/tests/test_suite.py
  asdf/versioning.py
  setup.cfg
Labels: no-changelog-entry-needed, testing
