Repository asdf-format/asdf, pull requests merged in 2019-04, with the labels that each got.

#668 Use yaml.safe_load in test cases
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/schema_tester.py
  setup.cfg
Labels: no-changelog-entry-needed, testing

#674 Don't use conda to install tox deps. Update documentation.
  README.rst
  tox.ini
Labels: no-changelog-entry-needed

#673 Make NDArrayType.__len__() a method, not a property
  CHANGES.rst
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_ndarray.py
Labels: bug

#675 add .eggs to gitignore
  .gitignore
Labels: no-changelog-entry-needed

#676 Automatically register the schema tester pytest plugin
  CHANGES.rst
  asdf/extension.py
  asdf/version.py
  conftest.py
  docs/asdf/extensions.rst
  pytest_asdf/__init__.py
  pytest_asdf/extension.py
  pytest_asdf/plugin.py
  setup.cfg
Labels: testing
