Repository asdf-format/asdf, pull requests merged in 2019-12, with the labels that each got.

#682 Fix load_schema memory issue and add convenience function for fetching the default resolver.
  CHANGES.rst
  asdf/asdf.py
  asdf/extension.py
  asdf/resolver.py
  asdf/schema.py
  asdf/tests/test_api.py
  asdf/tests/test_resolver.py
  asdf/tests/test_schema.py
Labels: bug, enhancement

#716 Refresh NDArrayType when underlying mmap is closed
  CHANGES.rst
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_ndarray.py
Labels: bug

#721 Fix broken codecov.io badge
  README.rst
Labels: no-changelog-entry-needed

#722 Ignore failing schema tests on astropy < 4.0
  asdf/tests/test_schema.py
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed

#727 fix gwcs import of WCSType tag, changed in 0.12.0
  asdf/tests/test_asdftypes.py
Labels: no-changelog-entry-needed, testing
