Repository asdf-format/asdf, pull requests merged in 2020-04, with the labels that each got.

#777 Support (de)serialization of custom objects containing implicit references
  CHANGES.rst
  asdf/asdf.py
  asdf/reference.py
  asdf/schema.py
  asdf/tags/core/__init__.py
  asdf/tags/core/integer.py
  asdf/tags/core/ndarray.py
  asdf/tests/data/fraction_with_inverse-1.0.0.yaml
  asdf/tests/test_asdftypes.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_reference.py
  asdf/tests/test_schema.py
  asdf/tests/test_treeutil.py
  asdf/tests/test_yaml.py
  asdf/treeutil.py
  asdf/types.py
  asdf/yamlutil.py
  docs/asdf/extensions.rst
Labels: enhancement

#779 Fix history entries initialization
  CHANGES.rst
  asdf/asdf.py
  asdf/tests/test_api.py
Labels: bug

#781 Update developer overview documentation
  CHANGES.rst
  docs/asdf/developer_overview.rst
Labels: Docs

#783 Update changelogs for 2.6.0 release
  CHANGES.rst
  docs/asdf/changes.rst
Labels: no-changelog-entry-needed

#786 Fix diffing of simplified ndarray
  CHANGES.rst
  asdf/commands/diff.py
  asdf/commands/tests/data/simple_inline_array.diff
  asdf/commands/tests/data/simple_inline_array0.asdf
  asdf/commands/tests/data/simple_inline_array1.asdf
  asdf/commands/tests/test_diff.py
Labels: bug
