Repository asdf-format/asdf, pull requests merged in 2020-01, with the labels that each got.

#728 Add 'package' property to ExtensionMetadata and deprecate 'software'
  CHANGES.rst
  asdf/asdf.py
  asdf/tags/core/__init__.py
  asdf/tags/core/tests/test_extension_metadata.py
  asdf/tags/core/tests/test_history.py
  asdf/tests/data/asdf-2.5.0-empty.asdf
  asdf/tests/data/extension_check.fits
  asdf/tests/test_legacy_formats.py
Labels: bug

#710 Make AsdfDeprecationWarning a subclass of DeprecationWarning
  CHANGES.rst
  asdf/exceptions.py
Labels: enhancement

#732 Add tox environment that runs tests against an installed asdf package
  .travis.yml
  CHANGES.rst
  asdf/tests/test_api.py
  tox.ini
Labels: testing

#734 2.5.1x
  .travis.yml
  CHANGES.rst
  asdf/tests/test_api.py
  asdf/tests/test_asdftypes.py
  docs/asdf/changes.rst
  tox.ini
Labels: no-changelog-entry-needed

#741 Update setup.cfg minimum Python version
  setup.cfg
Labels: no-changelog-entry-needed

#740 Clean up tox and travis configs, add new builds
  .travis.yml
  tox.ini
Labels: no-changelog-entry-needed

#743 Fix tests on s390x
  .travis.yml
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_array_blocks.py
Labels: no-changelog-entry-needed
