Repository asdf-format/asdf, pull requests merged in 2020-07, with the labels that each got.

#821 Fix bug in version map caching
  CHANGES.rst
  asdf/versioning.py
Labels: bug

#822 Clean up tox env dependencies
  tox.ini
Labels: no-changelog-entry-needed, testing

#827 Allow arrays to be written to blocks in non-contiguous order
  CHANGES.rst
  asdf/block.py
  asdf/generic_io.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_ndarray.py
Labels: bug

#785 Fix validation of default values in schemas
  CHANGES.rst
  asdf/schema.py
  setup.cfg
Labels: bug

#830 Update CHANGES.rst for 2.7.0 release
  CHANGES.rst
Labels: no-changelog-entry-needed

#832 Prevent errors when extra properties are present in extension metadata
  CHANGES.rst
  asdf/asdf.py
  asdf/tags/core/__init__.py
  asdf/tags/core/tests/test_extension_metadata.py
  asdf/tests/test_api.py
Labels: bug

#834 Alias open_asdf --> open in a more normal way
  asdf/__init__.py
Labels: no-changelog-entry-needed

#837 Restrict pytest to versions < 6
  setup.cfg
Labels: no-changelog-entry-needed
