Repository asdf-format/asdf, pull requests merged in 2022-01, with the labels that each got.

#1052 added support for __asdf_traverse__ method to allow custom introspect…
  CHANGES.rst
  asdf/_display.py
  asdf/tests/test_api.py
  docs/asdf/extending/extensions.rst
  docs/asdf/features.rst
Labels: enhancement

#1056 Fixed bugs zsh in readme
  README.rst
Labels: no-changelog-entry-needed

#1055 fixed search for __asdf_traverse__ capability
  CHANGES.rst
  asdf/search.py
Labels: bug
