Repository asdf-format/asdf, pull requests merged in 2022-10, with the labels that each got.

#1201 Fix typo in docs
  docs/conf.py
Labels: no-changelog-entry-needed

#1185 Stop subclassing JSONSchema validator
  CHANGES.rst
  asdf/schema.py
  asdf/tests/test_schema.py
  docs/asdf/config.rst
  pyproject.toml
Labels: Downstream CI

#1203 Unpin jsonschema, fix default validation
  CHANGES.rst
  asdf/schema.py
  asdf/tests/test_schema.py
Labels: Downstream CI

#1209 Update pre-commit with yesqa
  .pre-commit-config.yaml
  docs/conf.py
Labels: no-changelog-entry-needed

#1211 Update action versions
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .github/workflows/s390x.yml
Labels: no-changelog-entry-needed, Downstream CI, s390x

#1219 Use released python 3.11 runner
  .github/workflows/ci.yml
Labels: no-changelog-entry-needed

#1220 Switch to using ruff
  .flake8
  .pre-commit-config.yaml
  asdf/compression.py
  asdf/tests/test_array_blocks.py
  asdf/tests/test_compression.py
  pyproject.toml
Labels: no-changelog-entry-needed

#1217 change use of tmpdir to tmp_path in tests
  asdf/tests/helpers.py
  asdf/tests/httpserver.py
  asdf/tests/test_api.py
  asdf/tests/test_array_blocks.py
  asdf/tests/test_asdf.py
  asdf/tests/test_compression.py
  asdf/tests/test_file_format.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_helpers.py
  asdf/tests/test_info.py
  asdf/tests/test_integration.py
  asdf/tests/test_reference.py
  asdf/tests/test_schema.py
  asdf/tests/test_stream.py
  asdf/tests/test_types.py
  asdf/tests/test_yaml.py
Labels: no-changelog-entry-needed, Downstream CI

#1218 Turn warnings into errors
  .github/workflows/ci.yml
  asdf/commands/tests/test_diff.py
  asdf/tests/test_asdf.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  pyproject.toml
  tox.ini
Labels: no-changelog-entry-needed

#1221 close files opened during a failed call to asdf.open
  CHANGES.rst
  asdf/asdf.py
  asdf/tests/test_asdf.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
Labels: Downstream CI

#1225 Cleanup some strings
  asdf/asdf.py
  asdf/block.py
  asdf/commands/edit.py
  asdf/commands/extension.py
  asdf/commands/extract.py
  asdf/entry_points.py
  asdf/extension/_converter.py
  asdf/extension/_legacy.py
  asdf/extension/_manager.py
  asdf/fits_embed.py
  asdf/resource.py
  asdf/schema.py
  asdf/tags/core/external_reference.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_history.py
  asdf/tests/test_api.py
  asdf/tests/test_array_blocks.py
  asdf/tests/test_asdf.py
  asdf/tests/test_entry_points.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_helpers.py
  asdf/tests/test_resource.py
  asdf/tests/test_schema.py
  asdf/tests/test_stream.py
  asdf/tests/test_types.py
  asdf/tests/test_yaml.py
  asdf/treeutil.py
  asdf/types.py
  asdf/yamlutil.py
Labels: no-changelog-entry-needed, refactoring
