Repository asdf-format/asdf, pull requests merged in 2022-11, with the labels that each got.

#1228 Add fsspec http support
  CHANGES.rst
  asdf/generic_io.py
  asdf/tests/test_asdf.py
  asdf/tests/test_generic_io.py
  pyproject.toml
Labels: Downstream CI

#1230 Feature/whole file memmap
  CHANGES.rst
  asdf/asdf.py
  asdf/block.py
  asdf/commands/edit.py
  asdf/generic_io.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_array_blocks.py
Labels: Downstream CI

#1234 Fix handling of NDArrayType during block to fits hdu matching
  CHANGES.rst
  asdf/fits_embed.py
  asdf/tests/test_fits_embed.py
  asdf/util.py
Labels: Downstream CI

#1224 Add a codeowners file
  .github/CODEOWNERS
Labels: no-changelog-entry-needed

#1235 update changelog for 2.14.0 release
  CHANGES.rst
Labels: no-changelog-entry-needed, Downstream CI

#1236 Bugfix s390x CI
  .github/workflows/s390x.yml
Labels: no-changelog-entry-needed, s390x

#1238 Add jsonschem to devdeps
  requirements-dev.txt
Labels: no-changelog-entry-needed

#1241 always close memmaps with the asdf file
  CHANGES.rst
  asdf/generic_io.py
  asdf/tags/core/tests/test_ndarray.py
Labels: Downstream CI

#1243 update changelog for 2.14.1
  CHANGES.rst
Labels: no-changelog-entry-needed

#1237 Remove dead docker file
  docker/s390x/Dockerfile
  docker/s390x/README.md
Labels: no-changelog-entry-needed

#1247 use pytest to parametrize test_version_map_support
  asdf/tests/test_versioning.py
Labels: no-changelog-entry-needed

#1252 more test skips to prep for asdf-standard 1.6 update
  asdf/tests/test_versioning.py
Labels: no-changelog-entry-needed
