Repository asdf-format/asdf, pull requests merged in 2022-03, with the labels that each got.

#1098 Added condition for label to run downstream tests as part of PR
  .github/workflows/downstream.yml
Labels: no-changelog-entry-needed, Downstream CI

#1099 Update changes for release 2.10.1
  CHANGES.rst
  docs/asdf/changes.rst
Labels: no-changelog-entry-needed

#1100 Merge latest changes on master back to 3.0 epic
  .github/workflows/downstream.yml
  .pre-commit-config.yaml
  CHANGES.rst
  asdf/_convenience.py
  asdf/asdf.py
  asdf/core/__init__.py
  asdf/core/_converters/tests/test_entities.py
  asdf/core/_validators/ndarray.py
  asdf/extension/_manager.py
  asdf/resource.py
  asdf/schema.py
  asdf/tests/test_api.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_integration.py
  asdf/tests/test_resource.py
  asdf/tests/test_schema.py
  asdf/tests/test_versioning.py
  asdf/type_index.py
  bandit.yaml
  docs/asdf/changes.rst
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: no-changelog-entry-needed

#1101 Update setuptools_scm configuration
  .gitignore
  asdf/__init__.py
  asdf/_helpers.py
  asdf/asdf.py
  asdf/tests/test_entry_points.py
  pyproject.toml
  setup.py
Labels: no-changelog-entry-needed

#1103 Fix style issues from #1092
  asdf/extension/__init__.py
Labels: no-changelog-entry-needed

#1106 Add stdatamodels to downstream
  .github/workflows/downstream.yml
Labels: no-changelog-entry-needed, Downstream CI

#1107 Pin pytest to < 7.1 for Windows
  setup.cfg
Labels: no-changelog-entry-needed

#1105 Update jsonschema to 4.x
  CHANGES.rst
  asdf/schema.py
  asdf/tests/test_schema.py
  setup.cfg
  tox.ini
Labels: Downstream CI

#1108 Updates for release 2.11.0
  CHANGES.rst
  docs/asdf/changes.rst
Labels: no-changelog-entry-needed

#1112 Merge master into asdf-3.0-epic
  .github/workflows/downstream.yml
  .gitignore
  CHANGES.rst
  asdf/__init__.py
  asdf/_helpers.py
  asdf/asdf.py
  asdf/schema.py
  asdf/tests/test_entry_points.py
  asdf/tests/test_schema.py
  docs/asdf/changes.rst
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: no-changelog-entry-needed

#1118 Bugfix for name of changes entry in docs
  .pre-commit-config.yaml
  docs/asdf/changes.rst
  setup.cfg
Labels: no-changelog-entry-needed

#1124 Clarified statement about default ASDF version
  docs/asdf/config.rst
Labels: no-changelog-entry-needed

#1125 Update warnings job to python 3.10
  .github/workflows/ci.yml
Labels: no-changelog-entry-needed
