Repository asdf-format/asdf, pull requests merged in 2023-02, with the labels that each got.

#1344 don't call reserve_blocks on types that have converters
  asdf/block.py
Labels: no-changelog-entry-needed, Downstream CI

#1336 add AsdfDeprecationWarning to AsdfFile.blocks
  CHANGES.rst
  asdf/asdf.py
  asdf/block.py
  asdf/commands/tests/test_defragment.py
  asdf/commands/tests/test_exploded.py
  asdf/commands/tests/test_to_yaml.py
  asdf/fits_embed.py
  asdf/stream.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_integer.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/helpers.py
  asdf/tests/test_api.py
  asdf/tests/test_array_blocks.py
  asdf/tests/test_asdf.py
  asdf/tests/test_compression.py
  asdf/tests/test_file_format.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_stream.py
  pytest_asdf/plugin.py
  tox.ini
Labels: Downstream CI

#1352 Remove pyupgrade use from pre-commit
  .pre-commit-config.yaml
  pyproject.toml
Labels: no-changelog-entry-needed

#1349 add crds environment variables to stdatamodels ci
  .github/workflows/downstream.yml
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI

#1358 remove crds cache ci job
  .github/workflows/downstream.yml
Labels: no-changelog-entry-needed, Downstream CI

#1360 Add oldest dependencies testing
  .github/workflows/ci.yml
  CHANGES.rst
  pyproject.toml
  tox.ini
Labels: Downstream CI

#1355 clean up duplicate tests and combine similar
  asdf/tests/test_generic_io.py
Labels: no-changelog-entry-needed

#1328 Add new plugin type for custom schema validators
  CHANGES.rst
  asdf/core/__init__.py
  asdf/core/_extensions.py
  asdf/core/_integration.py
  asdf/core/_validators/__init__.py
  asdf/core/_validators/ndarray.py
  asdf/core/tests/__init__.py
  asdf/core/tests/test_integration.py
  asdf/exceptions.py
  asdf/extension/__init__.py
  asdf/extension/_extension.py
  asdf/extension/_manager.py
  asdf/extension/_manifest.py
  asdf/extension/_validator.py
  asdf/resource.py
  asdf/schema.py
  asdf/tags/core/ndarray.py
  asdf/tests/test_config.py
  asdf/tests/test_extension.py
  asdf/tests/test_resource.py
  docs/asdf/extending/extensions.rst
  docs/asdf/extending/use_cases.rst
  docs/asdf/extending/validators.rst
  docs/index.rst
  pyproject.toml
Labels: Downstream CI

#1359 add deprecation to CustomType
  CHANGES.rst
  asdf/entry_points.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/__init__.py
  asdf/tests/objects.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_helpers.py
  asdf/tests/test_schema.py
  asdf/tests/test_types.py
  asdf/types.py
  pyproject.toml
  tox.ini
Labels: Downstream CI

#1365 Make the warning only issue on the very first subclass of `CustomType`
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_types.py
  asdf/types.py
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1367 Backport PR #1365 on branch 2.15.x (Make the warning only issue on the very first subclass of `CustomType`)
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_types.py
  asdf/types.py
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1369 Add label checker CI
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1372 Move label check to using `any_of` instead of `one_of`
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x, development

#1371 Add note to contributing guide about backport labels
  CONTRIBUTING.rst
Labels: no-changelog-entry-needed, backport-2.15.x, development

#1370 Backport PR #1369 on branch 2.15.x (Add label checker CI)
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1380 Document how to use the meeseeks bot
  CONTRIBUTING.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1381 Backport PR #1380 on branch 2.15.x (Document how to use the meeseeks bot)
  CONTRIBUTING.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1383 Remove warning ignores from CI
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1337 deprecate AsdfInFits
  CHANGES.rst
  asdf/commands/extract.py
  asdf/commands/remove_hdu.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_remove_hdu.py
  asdf/fits_embed.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_fits_embed.py
  docs/asdf/features.rst
  docs/conf.py
  pyproject.toml
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1384 Backport PR #1383 on branch 2.15.x (Remove warning ignores from CI)
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1362 deprecate asdf.resolver submodule
  CHANGES.rst
  asdf/_resolver.py
  asdf/extension/_legacy.py
  asdf/resolver.py
  asdf/tests/helpers.py
  asdf/tests/test_api.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_resolver.py
  asdf/tests/test_schema.py
  pyproject.toml
Labels: Downstream CI, backport-2.15.x

#1387 Backport PR #1337 on branch 2.15.x (deprecate AsdfInFits)
  CHANGES.rst
  asdf/commands/extract.py
  asdf/commands/remove_hdu.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_remove_hdu.py
  asdf/fits_embed.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_fits_embed.py
  docs/asdf/features.rst
  docs/conf.py
  pyproject.toml
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1390 Backport PR #1362 on branch 2.15.x (deprecate asdf.resolver submodule)
  CHANGES.rst
  asdf/_resolver.py
  asdf/extension/_legacy.py
  asdf/resolver.py
  asdf/tests/helpers.py
  asdf/tests/test_api.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_resolver.py
  asdf/tests/test_schema.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1394 Fix bug with running tests in ASDF from path outside asdf
  asdf/conftest.py
  pyproject.toml
Labels: no-changelog-entry-needed, backport-2.15.x

#1391 Add a scheduled workflow
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .github/workflows/s390x.yml
  .github/workflows/scheduled.yml
Labels: no-changelog-entry-needed, Downstream CI, s390x, backport-2.15.x

#1398 Backport PR #1391 on branch 2.15.x (Add a scheduled workflow)
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .github/workflows/s390x.yml
  .github/workflows/scheduled.yml
Labels: no-changelog-entry-needed, Downstream CI, s390x, backport-2.15.x

#1397 Backport PR #1394 on branch 2.15.x (Fix bug with running tests in ASDF from path outside asdf)
  asdf/conftest.py
  pyproject.toml
Labels: no-changelog-entry-needed, backport-2.15.x

#1399 Add concurrency cancellations to workflows
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .github/workflows/label.yml
  .github/workflows/s390x.yml
Labels: no-changelog-entry-needed, Downstream CI, s390x, backport-2.15.x

#1402 Backport PR #1399 on branch 2.15.x (Add concurrency cancellations to workflows)
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .github/workflows/label.yml
  .github/workflows/s390x.yml
Labels: no-changelog-entry-needed, Downstream CI, s390x, backport-2.15.x

#1405 Remove concurrency cancel for `Label Checker` job
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1406 Backport PR #1405 on branch 2.15.x (Remove concurrency cancel for `Label Checker` job)
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1395 remove asdf.compat
  asdf/compat/__init__.py
  asdf/compat/numpycompat.py
  asdf/tests/test_yaml.py
Labels: no-changelog-entry-needed, backport-2.15.x

#1408 Use reusable changelog workflow
  .github/workflows/changelog.yml
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1410 Backport PR #1408 on branch 2.15.x (Use reusable changelog workflow)
  .github/workflows/changelog.yml
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1407 Backport PR #1395 on branch 2.15.x (remove asdf.compat)
  asdf/compat/__init__.py
  asdf/compat/numpycompat.py
  asdf/tests/test_yaml.py
Labels: no-changelog-entry-needed, backport-2.15.x

#1396 Consolidate toxenvs
  .github/workflows/ci.yml
  tox.ini
Labels: testing, no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1412 Backport PR #1396 on branch 2.15.x (Consolidate toxenvs)
  .github/workflows/ci.yml
  tox.ini
Labels: testing, no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1415 Backport PR #1414 on branch 2.15.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  asdf/commands/edit.py
  asdf/commands/tests/test_edit.py
  asdf/tests/__init__.py
  asdf/tests/test_api.py
  asdf/tests/test_array_blocks.py
  asdf/tests/test_compression.py
  pyproject.toml
Labels: no-changelog-entry-needed, backport-2.15.x

#1388 Deprecate/assert extension correctness
  CHANGES.rst
  asdf/tests/helpers.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
Labels: Downstream CI, backport-2.15.x

#1413 Automatically set automerge for meeseeksmachine
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1419 Backport PR #1413 on branch 2.15.x (Automatically set automerge for meeseeksmachine)
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1418 Backport PR #1388 on branch 2.15.x (Deprecate/assert extension correctness)
  CHANGES.rst
  asdf/tests/helpers.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
Labels: Downstream CI, backport-2.15.x

#1389 run jwst downstream tests in parallel
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1403 deprecate type_index
  CHANGES.rst
  asdf/_type_index.py
  asdf/conftest.py
  asdf/extension/_legacy.py
  asdf/tests/test_deprecated.py
  asdf/type_index.py
Labels: Downstream CI, backport-2.15.x

#1421 Backport PR #1403 on branch 2.15.x (deprecate type_index)
  CHANGES.rst
  asdf/_type_index.py
  asdf/conftest.py
  asdf/extension/_legacy.py
  asdf/tests/test_deprecated.py
  asdf/type_index.py
Labels: Downstream CI, backport-2.15.x

#1411 add warning to asdftool extract and remove-hdu commands
  CHANGES.rst
  asdf/commands/extract.py
  asdf/commands/remove_hdu.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_remove_hdu.py
Labels: backport-2.15.x

#1417 deprecate AsdfFile attrs and methods that use legacy extension api
  CHANGES.rst
  asdf/asdf.py
  asdf/block.py
  asdf/commands/tags.py
  asdf/commands/tests/test_tags.py
  asdf/schema.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/helpers.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_schema.py
  asdf/yamlutil.py
Labels: Downstream CI, backport-2.15.x

#1423 Backport PR #1411 on branch 2.15.x (add warning to asdftool extract and remove-hdu commands)
  CHANGES.rst
  asdf/commands/extract.py
  asdf/commands/remove_hdu.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_remove_hdu.py
Labels: backport-2.15.x

#1416 Add dependabot configuration
  .github/dependabot.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1422 Fix some warnings raised by the changelog CI
  CHANGES.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1425 Backport PR #1422 on branch 2.15.x (Fix some warnings raised by the changelog CI)
  CHANGES.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1424 Backport PR #1416 on branch 2.15.x (Add dependabot configuration)
  .github/dependabot.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1401 deprecate asdf.types
  CHANGES.rst
  asdf/__init__.py
  asdf/_types.py
  asdf/asdftypes.py
  asdf/conftest.py
  asdf/entry_points.py
  asdf/extension/_legacy.py
  asdf/reference.py
  asdf/tags/core/__init__.py
  asdf/tags/core/complex.py
  asdf/tags/core/constant.py
  asdf/tags/core/external_reference.py
  asdf/tags/core/integer.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_history.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_helpers.py
  asdf/tests/test_schema.py
  asdf/tests/test_types.py
  asdf/types.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1427 Backport PR #1417 on branch 2.15.x (deprecate AsdfFile attrs and methods that use legacy extension api)
  CHANGES.rst
  asdf/asdf.py
  asdf/block.py
  asdf/commands/tags.py
  asdf/commands/tests/test_tags.py
  asdf/schema.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/helpers.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_schema.py
  asdf/yamlutil.py
Labels: Downstream CI, backport-2.15.x

#1428 Backport PR #1401 on branch 2.15.x (deprecate asdf.types)
  CHANGES.rst
  asdf/__init__.py
  asdf/_types.py
  asdf/asdftypes.py
  asdf/conftest.py
  asdf/entry_points.py
  asdf/extension/_legacy.py
  asdf/reference.py
  asdf/tags/core/__init__.py
  asdf/tags/core/complex.py
  asdf/tags/core/constant.py
  asdf/tags/core/external_reference.py
  asdf/tags/core/integer.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_history.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_helpers.py
  asdf/tests/test_schema.py
  asdf/tests/test_types.py
  asdf/types.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1409 deprecation asdf.extension legacy functions
  CHANGES.rst
  asdf/asdf.py
  asdf/extension/__init__.py
  asdf/schema.py
  asdf/tests/helpers.py
  asdf/tests/test_api.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_schema.py
  asdf/tests/test_versioning.py
  pytest_asdf/plugin.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1430 Backport PR #1409 on branch 2.15.x (deprecation asdf.extension legacy functions)
  CHANGES.rst
  asdf/asdf.py
  asdf/extension/__init__.py
  asdf/schema.py
  asdf/tests/helpers.py
  asdf/tests/test_api.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_schema.py
  asdf/tests/test_versioning.py
  pytest_asdf/plugin.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1426 Fix for missed warning supression
  asdf/tests/test_file_format.py
Labels: no-changelog-entry-needed, backport-2.15.x

#1432 Backport PR #1426 on branch 2.15.x (Fix for missed warning supression)
  asdf/tests/test_file_format.py
Labels: no-changelog-entry-needed, backport-2.15.x

#1433 move format_tag to testing.helpers
  CHANGES.rst
  asdf/_types.py
  asdf/testing/helpers.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_schema.py
Labels: backport-2.15.x

#1435 Backport PR #1433 on branch 2.15.x (move format_tag to testing.helpers)
  CHANGES.rst
  asdf/_types.py
  asdf/testing/helpers.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_schema.py
Labels: backport-2.15.x

#1429 Deprecate AsdfExtension, AsdfExtensionList, BuiltinExtension
  CHANGES.rst
  asdf/__init__.py
  asdf/asdf.py
  asdf/entry_points.py
  asdf/extension/__init__.py
  asdf/tests/test_asdf.py
  asdf/tests/test_config.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_types.py
  asdf/tests/test_util.py
  pyproject.toml
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1434 Resolve `PT011` error code
  asdf/commands/tests/test_diff.py
  asdf/tags/core/tests/test_complex.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_api.py
  asdf/tests/test_array_blocks.py
  asdf/tests/test_asdf.py
  asdf/tests/test_compression.py
  asdf/tests/test_config.py
  asdf/tests/test_extension.py
  asdf/tests/test_file_format.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_helpers.py
  asdf/tests/test_integration.py
  asdf/tests/test_reference.py
  asdf/tests/test_resolver.py
  asdf/tests/test_resource.py
  asdf/tests/test_schema.py
  asdf/tests/test_search.py
  asdf/tests/test_stream.py
  asdf/tests/test_types.py
  asdf/tests/test_yaml.py
  pyproject.toml
Labels: no-changelog-entry-needed, backport-2.15.x

#1437 Backport PR #1434 on branch 2.15.x (Resolve `PT011` error code)
  asdf/commands/tests/test_diff.py
  asdf/tags/core/tests/test_complex.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_api.py
  asdf/tests/test_array_blocks.py
  asdf/tests/test_asdf.py
  asdf/tests/test_compression.py
  asdf/tests/test_config.py
  asdf/tests/test_extension.py
  asdf/tests/test_file_format.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_helpers.py
  asdf/tests/test_integration.py
  asdf/tests/test_reference.py
  asdf/tests/test_resolver.py
  asdf/tests/test_resource.py
  asdf/tests/test_schema.py
  asdf/tests/test_search.py
  asdf/tests/test_stream.py
  asdf/tests/test_types.py
  asdf/tests/test_yaml.py
  pyproject.toml
Labels: no-changelog-entry-needed, backport-2.15.x

#1436 Backport PR #1429 on branch 2.15.x (Deprecate AsdfExtension, AsdfExtensionList, BuiltinExtension)
  CHANGES.rst
  asdf/__init__.py
  asdf/asdf.py
  asdf/entry_points.py
  asdf/extension/__init__.py
  asdf/tests/test_asdf.py
  asdf/tests/test_config.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_types.py
  asdf/tests/test_util.py
  pyproject.toml
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1438 Backport PR #1431 on branch 2.15.x (Drop unnecessary suppressions from the tox jobs)
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1361 deprecate asdf_extensions entry point
  CHANGES.rst
  asdf/entry_points.py
  asdf/tests/helpers.py
  asdf/tests/test_asdf.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_entry_points.py
  asdf/tests/test_types.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1439 Backport PR #1361 on branch 2.15.x (deprecate asdf_extensions entry point)
  CHANGES.rst
  asdf/entry_points.py
  asdf/tests/helpers.py
  asdf/tests/test_asdf.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_entry_points.py
  asdf/tests/test_types.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1440 deprecate asdf.tests.helpers
  CHANGES.rst
  asdf/commands/tests/test_defragment.py
  asdf/commands/tests/test_diff.py
  asdf/commands/tests/test_exploded.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_info.py
  asdf/commands/tests/test_to_yaml.py
  asdf/conftest.py
  asdf/entry_points.py
  asdf/tags/core/tests/test_complex.py
  asdf/tags/core/tests/test_extension_metadata.py
  asdf/tags/core/tests/test_external_reference.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/core/tests/test_integer.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/_helpers.py
  asdf/tests/helpers.py
  asdf/tests/objects.py
  asdf/tests/test_api.py
  asdf/tests/test_asdf.py
  asdf/tests/test_compression.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_helpers.py
  asdf/tests/test_reference.py
  asdf/tests/test_reference_files.py
  asdf/tests/test_schema.py
  asdf/tests/test_types.py
  asdf/tests/test_yaml.py
  docs/asdf/developer_api.rst
  pyproject.toml
  pytest_asdf/plugin.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1442 Backport PR #1440 on branch 2.15.x (deprecate asdf.tests.helpers)
  CHANGES.rst
  asdf/commands/tests/test_defragment.py
  asdf/commands/tests/test_diff.py
  asdf/commands/tests/test_exploded.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_info.py
  asdf/commands/tests/test_to_yaml.py
  asdf/conftest.py
  asdf/entry_points.py
  asdf/tags/core/tests/test_complex.py
  asdf/tags/core/tests/test_extension_metadata.py
  asdf/tags/core/tests/test_external_reference.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/core/tests/test_integer.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/_helpers.py
  asdf/tests/helpers.py
  asdf/tests/objects.py
  asdf/tests/test_api.py
  asdf/tests/test_asdf.py
  asdf/tests/test_compression.py
  asdf/tests/test_deprecated.py
  asdf/tests/test_extension.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_helpers.py
  asdf/tests/test_reference.py
  asdf/tests/test_reference_files.py
  asdf/tests/test_schema.py
  asdf/tests/test_types.py
  asdf/tests/test_yaml.py
  docs/asdf/developer_api.rst
  pyproject.toml
  pytest_asdf/plugin.py
  tox.ini
Labels: Downstream CI, backport-2.15.x

#1443 add stpipe to downstream ci
  .github/workflows/downstream.yml
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1444 Backport PR #1443 on branch 2.15.x (add stpipe to downstream ci)
  .github/workflows/downstream.yml
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1449 Backport PR #1448 on branch 2.15.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  asdf/_convenience.py
  asdf/_types.py
  asdf/block.py
  asdf/commands/diff.py
  asdf/compression.py
  asdf/extension/_tag.py
  asdf/reference.py
  asdf/tests/test_extension.py
  asdf/treeutil.py
  asdf/versioning.py
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1446 clarify ASDF library versioning strategy
  docs/asdf/release_and_support.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1452 Backport PR #1446 on branch 2.15.x (clarify ASDF library versioning strategy)
  docs/asdf/release_and_support.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1445 Module shadowing
  asdf/resolver.py
  asdf/tests/helpers.py
  asdf/tests/test_deprecated.py
  asdf/type_index.py
  asdf/types.py
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1453 Backport PR #1445 on branch 2.15.x (Module shadowing)
  asdf/resolver.py
  asdf/tests/helpers.py
  asdf/tests/test_deprecated.py
  asdf/type_index.py
  asdf/types.py
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI, backport-2.15.x

#1451 respect umask when determining file permissions
  CHANGES.rst
  asdf/generic_io.py
  asdf/tests/test_generic_io.py
Labels: Downstream CI, backport-2.15.x
