Repository asdf-format/asdf, pull requests merged in 2023-01, with the labels that each got.

#1286 use HOME instead of ~ in crds path
  .github/workflows/downstream.yml
Labels: no-changelog-entry-needed, Downstream CI

#1274 Switch to using `tox` and openastronomy for downstream
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI

#1283 count blocks._internal_blocks during update
  asdf/asdf.py
Labels: no-changelog-entry-needed, Downstream CI

#1280 Discard cache of lazy-loaded block data when it is no longer referenced by the tree
  CHANGES.rst
  asdf/block.py
  asdf/tests/test_array_blocks.py
Labels: Downstream CI

#1284 remove redundant Block.readonly
  asdf/asdf.py
  asdf/block.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_ndarray.py
Labels: no-changelog-entry-needed, Downstream CI

#1296 Apply automatic formatter to pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
Labels: no-changelog-entry-needed

#1297 Use `--open-files`, `--run-slow`, and `--remote-data` flags for astropy downstream
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI

#1299 Add `pyupgrade` check to `ruff`
  asdf/tests/test_yaml.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1300 Add `pep8-naming` check to `ruff`
  asdf/extension/_compressor.py
  asdf/extension/_converter.py
  asdf/extension/_extension.py
  asdf/extension/_legacy.py
  asdf/reference.py
  asdf/resource.py
  asdf/schema.py
  asdf/tags/core/external_reference.py
  asdf/tags/core/ndarray.py
  asdf/tests/test_extension.py
  asdf/tests/test_types.py
  asdf/types.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1301 Add `flake8-bandit` check to `ruff`
  .pre-commit-config.yaml
  asdf/block.py
  asdf/schema.py
  asdf/tags/core/ndarray.py
  asdf/versioning.py
  asdf/yamlutil.py
  bandit.yaml
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1302 Add `flake8-blind-except` check to `ruff`
  asdf/commands/edit.py
  asdf/entry_points.py
  asdf/generic_io.py
  asdf/reference.py
  asdf/search.py
  asdf/tests/helpers.py
  asdf/tests/test_reference_files.py
  asdf/tests/test_versioning.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1303 Add `flake8-bugbear` check to `ruff`
  asdf/_display.py
  asdf/_node_info.py
  asdf/asdf.py
  asdf/block.py
  asdf/commands/diff.py
  asdf/commands/extract.py
  asdf/commands/main.py
  asdf/commands/remove_hdu.py
  asdf/compression.py
  asdf/entry_points.py
  asdf/fits_embed.py
  asdf/reference.py
  asdf/schema.py
  asdf/search.py
  asdf/tagged.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_extension_metadata.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/helpers.py
  asdf/tests/test_compression.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_schema.py
  asdf/tests/test_versioning.py
  asdf/type_index.py
  asdf/types.py
  asdf/util.py
  pyproject.toml
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI

#1304 Add `flake8-builtins` check to `ruff`
  asdf/__init__.py
  asdf/asdf.py
  asdf/block.py
  asdf/commands/defragment.py
  asdf/commands/exploded.py
  asdf/commands/main.py
  asdf/commands/to_yaml.py
  asdf/fits_embed.py
  asdf/generic_io.py
  asdf/resolver.py
  asdf/schema.py
  asdf/search.py
  asdf/tests/test_info.py
  asdf/tests/test_search.py
  asdf/versioning.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1305 Add `flake8-comprehensions` check to `ruff`
  asdf/asdf.py
  asdf/commands/diff.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_remove_hdu.py
  asdf/tags/core/integer.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/core/tests/test_integer.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_api.py
  asdf/tests/test_compression.py
  asdf/tests/test_helpers.py
  asdf/tests/test_info.py
  asdf/tests/test_schema.py
  asdf/tests/test_search.py
  asdf/tests/test_treeutil.py
  asdf/tests/test_types.py
  asdf/tests/test_util.py
  asdf/tests/test_yaml.py
  asdf/types.py
  compatibility_tests/test_file_compatibility.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1306 Add `flake8-errmsg` check to `ruff`
  asdf/_helpers.py
  asdf/asdf.py
  asdf/block.py
  asdf/commands/diff.py
  asdf/commands/edit.py
  asdf/commands/extract.py
  asdf/commands/tests/test_edit.py
  asdf/compression.py
  asdf/config.py
  asdf/extension/_converter.py
  asdf/extension/_extension.py
  asdf/extension/_manager.py
  asdf/extension/_manifest.py
  asdf/extension/_tag.py
  asdf/fits_embed.py
  asdf/generic_io.py
  asdf/reference.py
  asdf/resolver.py
  asdf/resource.py
  asdf/schema.py
  asdf/search.py
  asdf/tagged.py
  asdf/tags/core/integer.py
  asdf/tags/core/ndarray.py
  asdf/tests/test_entry_points.py
  asdf/tests/test_helpers.py
  asdf/tests/test_info.py
  asdf/tests/test_schema.py
  asdf/treeutil.py
  asdf/type_index.py
  asdf/types.py
  asdf/util.py
  asdf/yamlutil.py
  compatibility_tests/common.py
  pyproject.toml
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI

#1307 Add `flake8-implicit-str-concat` check to `ruff`
  asdf/_helpers.py
  asdf/asdf.py
  asdf/asdftypes.py
  asdf/block.py
  asdf/fits_embed.py
  asdf/resolver.py
  asdf/tags/core/integer.py
  asdf/tags/core/tests/test_complex.py
  asdf/tags/core/tests/test_history.py
  asdf/tags/core/tests/test_integer.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/helpers.py
  asdf/tests/test_api.py
  asdf/tests/test_compression.py
  asdf/tests/test_info.py
  asdf/tests/test_schema.py
  asdf/tests/test_types.py
  asdf/tests/test_versioning.py
  asdf/util.py
  asdf/yamlutil.py
  compatibility_tests/test_file_compatibility.py
  pyproject.toml
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI

#1308 Add `flake8-import-conventions` check to `ruff`
  asdf/tests/test_util.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1309 Add `flake8-print` check to `ruff`
  asdf/_convenience.py
  asdf/asdf.py
  asdf/commands/edit.py
  asdf/commands/extension.py
  asdf/tags/core/tests/test_ndarray.py
  pyproject.toml
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI

#1313 Add `flake8-tidy-imports` check for `ruff`
  asdf/commands/defragment.py
  asdf/commands/diff.py
  asdf/commands/edit.py
  asdf/commands/exploded.py
  asdf/commands/extension.py
  asdf/commands/info.py
  asdf/commands/main.py
  asdf/commands/tags.py
  asdf/commands/tests/test_exploded.py
  asdf/commands/tests/test_extension.py
  asdf/commands/tests/test_extract.py
  asdf/commands/tests/test_info.py
  asdf/commands/tests/test_main.py
  asdf/commands/tests/test_remove_hdu.py
  asdf/commands/tests/test_tags.py
  asdf/commands/tests/test_to_yaml.py
  asdf/commands/to_yaml.py
  asdf/compat/numpycompat.py
  asdf/extension/_converter.py
  asdf/extension/_extension.py
  asdf/extension/_legacy.py
  asdf/extension/_manager.py
  asdf/extension/_manifest.py
  asdf/tags/core/__init__.py
  asdf/tags/core/complex.py
  asdf/tags/core/constant.py
  asdf/tags/core/external_reference.py
  asdf/tags/core/integer.py
  asdf/tags/core/ndarray.py
  asdf/tests/__init__.py
  asdf/tests/helpers.py
  asdf/tests/httpserver.py
  asdf/tests/test_compression.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_types.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1314 Add `eradicate` check for `ruff`
  asdf/tags/core/ndarray.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1315 Add `pylint` check for `ruff`
  asdf/_display.py
  asdf/_node_info.py
  asdf/search.py
  asdf/tests/test_config.py
  asdf/tests/test_versioning.py
  pyproject.toml
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI

#1316 Add `flake8-pie` check for `ruff`
  asdf/extension/_compressor.py
  asdf/extension/_converter.py
  asdf/extension/_extension.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1317 Enable `ruff` specific checks
  asdf/generic_io.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_ndarray.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_yaml.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1318 Enable `ALL` `ruff` checks by default
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1321 Fix `COM812`, `ruff` errors
  asdf/_node_info.py
  asdf/asdf.py
  asdf/block.py
  asdf/commands/diff.py
  asdf/commands/extension.py
  asdf/commands/extract.py
  asdf/commands/info.py
  asdf/commands/remove_hdu.py
  asdf/commands/tags.py
  asdf/compression.py
  asdf/extension/_legacy.py
  asdf/extension/_manifest.py
  asdf/fits_embed.py
  asdf/generic_io.py
  asdf/schema.py
  asdf/tags/core/ndarray.py
  asdf/tags/core/tests/test_complex.py
  asdf/tags/core/tests/test_history.py
  asdf/tests/__init__.py
  asdf/tests/helpers.py
  asdf/tests/test_api.py
  asdf/tests/test_asdf.py
  asdf/tests/test_config.py
  asdf/tests/test_entry_points.py
  asdf/tests/test_extension.py
  asdf/tests/test_file_format.py
  asdf/tests/test_fits_embed.py
  asdf/tests/test_generic_io.py
  asdf/tests/test_info.py
  asdf/tests/test_integration.py
  asdf/tests/test_reference.py
  asdf/tests/test_schema.py
  asdf/tests/test_types.py
  asdf/tests/test_versioning.py
  asdf/tests/test_yaml.py
  asdf/yamlutil.py
  compatibility_tests/common.py
  compatibility_tests/test_file_compatibility.py
  pyproject.toml
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, Downstream CI

#1322 Apply the `flynt` tool
  .pre-commit-config.yaml
  asdf/tags/core/tests/test_complex.py
  asdf/tests/helpers.py
  asdf/tests/test_asdf.py
  asdf/tests/test_yaml.py
  asdf/yamlutil.py
  pyproject.toml
Labels: no-changelog-entry-needed

#1324 Revert #1280
  CHANGES.rst
  asdf/block.py
  asdf/tests/test_array_blocks.py
Labels: no-changelog-entry-needed

#1329 Update ruff to v0.0.231
  .pre-commit-config.yaml
  asdf/_display.py
  asdf/asdf.py
  asdf/block.py
  asdf/commands/diff.py
  asdf/commands/extract.py
  asdf/commands/tests/test_diff.py
  asdf/fits_embed.py
  asdf/generic_io.py
  asdf/search.py
  asdf/stream.py
  asdf/tags/core/complex.py
  asdf/tags/core/ndarray.py
  asdf/tests/test_types.py
  asdf/tests/test_versioning.py
  asdf/util.py
  compatibility_tests/assert_file_correct.py
  compatibility_tests/common.py
  compatibility_tests/generate_file.py
  compatibility_tests/test_file_compatibility.py
  conftest.py
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI

#1338 bump isort to 5.11.5
  .pre-commit-config.yaml
Labels: no-changelog-entry-needed

#1340 fix weldx ci job
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI

#1339 More ruff clean-ups
  .pre-commit-config.yaml
  asdf/block.py
  asdf/fits_embed.py
  asdf/generic_io.py
  asdf/tests/test_versioning.py
  asdf/types.py
  pyproject.toml
Labels: no-changelog-entry-needed
