Repository asdf-format/asdf, pull requests merged in 2023-04, with the labels that each got.

#1513 Backport PR #1512 on branch 2.15.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: backport-2.15.x

#1514 update label_checker ci job for 2.15.1
  .github/workflows/label.yml
Labels: no-changelog-entry-needed, backport-2.15.x

#1518 limit ruff rules
  asdf/__init__.py
  asdf/_convenience.py
  asdf/_tests/_helpers.py
  asdf/_tests/tags/core/tests/test_ndarray.py
  asdf/_tests/test_deprecated.py
  asdf/_tests/test_extension.py
  asdf/_tests/test_file_format.py
  asdf/_tests/test_generic_io.py
  asdf/_tests/test_reference_files.py
  asdf/_tests/test_search.py
  asdf/_tests/test_tagged.py
  asdf/_tests/test_types.py
  asdf/_tests/test_versioning.py
  asdf/_type_index.py
  asdf/_types.py
  asdf/asdf.py
  asdf/commands/edit.py
  asdf/commands/extension.py
  asdf/entry_points.py
  asdf/generic_io.py
  asdf/reference.py
  asdf/schema.py
  asdf/search.py
  asdf/tags/core/ndarray.py
  asdf/tests/helpers.py
  asdf/type_index.py
  asdf/types.py
  asdf/util.py
  asdf/versioning.py
  compatibility_tests/assert_file_correct.py
  compatibility_tests/common.py
  compatibility_tests/generate_file.py
  compatibility_tests/test_file_compatibility.py
  pyproject.toml
  pytest_asdf/plugin.py
Labels: no-changelog-entry-needed, development

#1500 Initial benchmarks
  .gitignore
  asv.conf.json
  benchmarks/__init__.py
  benchmarks/_utils.py
  benchmarks/asdf.py
  benchmarks/schema.py
  benchmarks/treeutil.py
  benchmarks/yamlutil.py
Labels: no-changelog-entry-needed, development

#1528 skip astropy dev testing for python 3.8
  requirements-dev.txt
Labels: no-changelog-entry-needed, development
