Repository asdf-format/asdf, pull requests merged in 2023-07, with the labels that each got.

#1567 fix docs dependencies
  CODE_OF_CONDUCT.md
  docs/asdf/CODE_OF_CONDUCT.md
  docs/asdf/CODE_OF_CONDUCT.rst
  docs/conf.py
  docs/index.rst
  pyproject.toml
Labels: no-changelog-entry-needed, development

#1585 fix jsonschema docs links in asdf.schema
  asdf/schema.py
Labels: no-changelog-entry-needed, development

#1557 test for valid fileno before creating RealFile
  CHANGES.rst
  asdf/_tests/test_generic_io.py
  asdf/generic_io.py
Labels: development

#1561 Allow converter deferral and move Reference to a converter
  CHANGES.rst
  asdf/_tests/test_extension.py
  asdf/core/_converters/reference.py
  asdf/core/_extensions.py
  asdf/extension/_converter.py
  asdf/extension/_manager.py
  asdf/reference.py
  asdf/yamlutil.py
  docs/asdf/extending/converters.rst
Labels: development

#1602 [benchmarks] add commit URL for showing commits when clicked
  asv.conf.json
Labels: no-changelog-entry-needed, development

#1606 BOT: Changelog check has moved
  .github/workflows/changelog.yml
Labels: no-changelog-entry-needed, development

#1605 convert numpy scalars to python types before yaml encoding
  CHANGES.rst
  asdf/_tests/test_yaml.py
  asdf/yamlutil.py
  requirements-dev.txt
Labels: Downstream CI, development

#1600 add load_schema to asdf.schema.__all__
  asdf/schema.py
Labels: no-changelog-entry-needed, development

#1589 add note about implicit tuple to list conversion on write/read
  docs/asdf/features.rst
Labels: no-changelog-entry-needed, development

#1573 move SerializationContext to asdf.extension and add it to docs
  asdf/_tests/test_asdf.py
  asdf/asdf.py
  asdf/extension/__init__.py
  asdf/extension/_converter.py
  asdf/extension/_serialization_context.py
  docs/asdf/developer_overview.rst
  docs/asdf/extending/converters.rst
Labels: no-changelog-entry-needed, Downstream CI, development
