Repository asdf-format/asdf, pull requests merged in 2023-03, with the labels that each got.

#1457 Backport PR #1456 on branch 2.15.x (Bugfix for flakyness of httpstat.us)
  asdf/tests/test_reference.py
Labels: no-changelog-entry-needed, backport-2.15.x

#1455 Backport PR #1451 on branch 2.15.x (respect umask when determining file permissions)
  CHANGES.rst
  asdf/generic_io.py
  asdf/tests/test_generic_io.py
Labels: Downstream CI, backport-2.15.x

#1459 Consolidate deprecations add deprecations page to docs
  asdf/_tests/test_asdf.py
  asdf/_tests/test_deprecated.py
  asdf/fits_embed.py
  asdf/resolver.py
  asdf/type_index.py
  asdf/types.py
  docs/asdf/asdf_tool.rst
  docs/asdf/deprecations.rst
  docs/asdf/developer_api.rst
  docs/asdf/extending/legacy.rst
  docs/conf.py
  docs/index.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1463 Backport PR #1459 on branch 2.15.x (Consolidate deprecations add deprecations page to docs)
  asdf/_tests/test_asdf.py
  asdf/_tests/test_deprecated.py
  asdf/fits_embed.py
  asdf/resolver.py
  asdf/type_index.py
  asdf/types.py
  docs/asdf/asdf_tool.rst
  docs/asdf/deprecations.rst
  docs/asdf/developer_api.rst
  docs/asdf/extending/legacy.rst
  docs/conf.py
  docs/index.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1466 Backport PR #1465 on branch 2.15.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: no-changelog-entry-needed, backport-2.15.x

#1470 np.product is deprecated in numpy 1.25
  asdf/block.py
  asdf/tags/core/ndarray.py
Labels: no-changelog-entry-needed, backport-2.15.x

#1471 Backport PR #1470 on branch 2.15.x (np.product is deprecated in numpy 1.25)
  asdf/block.py
  asdf/tags/core/ndarray.py
Labels: no-changelog-entry-needed, backport-2.15.x

#1288 Drop support for ASDF-in-FITS
  CHANGES.rst
  asdf/_tests/commands/tests/test_diff.py
  asdf/_tests/commands/tests/test_extract.py
  asdf/_tests/commands/tests/test_remove_hdu.py
  asdf/_tests/data/asdf.fits.gz
  asdf/_tests/data/extension_check.fits
  asdf/_tests/data/version_mismatch.fits
  asdf/_tests/test_asdf.py
  asdf/_tests/test_deprecated.py
  asdf/_tests/test_file_format.py
  asdf/_tests/test_fits_embed.py
  asdf/asdf.py
  asdf/block.py
  asdf/commands/__init__.py
  asdf/commands/edit.py
  asdf/commands/extract.py
  asdf/commands/remove_hdu.py
  asdf/fits_embed.py
  asdf/tags/core/ndarray.py
  asdf/util.py
  docs/asdf/asdf_tool.rst
  docs/asdf/deprecations.rst
  docs/asdf/features.rst
  docs/asdf/user_api.rst
  pyproject.toml
Labels: Downstream CI, development

#1467 remove astropy and specutils from downstream
  .github/workflows/downstream.yml
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI, development

#1480 Bugfix for docs on python 3.11
  .readthedocs.yaml
  docs/conf.py
  docs/rtd_environment.yaml
Labels: no-changelog-entry-needed, backport-2.15.x

#1481 Backport PR #1480 on branch 2.15.x (Bugfix for docs on python 3.11)
  .readthedocs.yaml
  docs/conf.py
  docs/rtd_environment.yaml
Labels: no-changelog-entry-needed, backport-2.15.x

#1483 Backport PR #1482 on branch 2.15.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  asdf/_display.py
  asdf/config.py
  asdf/generic_io.py
  asdf/resource.py
  docs/asdf/extending/resources.rst
  docs/asdf/extending/uris.rst
  pyproject.toml
Labels: no-changelog-entry-needed, backport-2.15.x

#1479 rename master branch to main
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/scheduled.yml
  CHANGES.rst
  CONTRIBUTING.rst
  README.rst
  docs/asdf/developer_versioning.rst
Labels: backport-2.15.x

#1484 Backport PR #1479 on branch 2.15.x (rename master branch to main)
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/scheduled.yml
  CHANGES.rst
  CONTRIBUTING.rst
  README.rst
  docs/asdf/developer_versioning.rst
Labels: backport-2.15.x

#1487 add upper pin to jsonschema
  CHANGES.rst
  pyproject.toml
  requirements-dev.txt
Labels: backport-2.15.x

#1489 Backport PR #1487: add upper pin to jsonschema
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .pre-commit-config.yaml
  CHANGES.rst
  pyproject.toml
Labels: no-changelog-entry-needed, Downstream CI, Manual Backport

#1491 Forward port changelog changes for 2.14.4 release
  CHANGES.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1494 Backport PR #1493 on branch 2.15.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  pyproject.toml
Labels: no-changelog-entry-needed, backport-2.15.x

#1468 Move array storage settings to config
  CHANGES.rst
  asdf/_tests/test_array_blocks.py
  asdf/_tests/test_compression.py
  asdf/_tests/test_config.py
  asdf/asdf.py
  asdf/block.py
  asdf/config.py
  asdf/tags/core/ndarray.py
  docs/asdf/config.rst
Labels: development

#1501 Remove LTS statement
  docs/asdf/developer_api.rst
  docs/asdf/release_and_support.rst
  docs/asdf/user_api.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1502 Backport PR #1501 on branch 2.15.x (Remove LTS statement)
  docs/asdf/developer_api.rst
  docs/asdf/release_and_support.rst
  docs/asdf/user_api.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1473 add key support to block manager
  asdf/_tests/test_array_blocks.py
  asdf/block.py
Labels: no-changelog-entry-needed, development

#1469 Block data callback
  asdf/_tests/test_array_blocks.py
  asdf/block.py
Labels: no-changelog-entry-needed, development

#1504 update changelog for 2.15.0 release
  .readthedocs.yaml
  CHANGES.rst
Labels: no-changelog-entry-needed, backport-2.15.x

#1509 Backport PR #1504 on branch 2.15.x (update changelog for 2.15.0 release)
  .readthedocs.yaml
  CHANGES.rst
Labels: no-changelog-entry-needed, backport-2.15.x, Manual Backport
