Repository asdf-format/asdf, pull requests merged in 2024-08, with the labels that each got.

#1815 MNT: handle a deprecation warning from `attrs` v24.1.0
  CHANGES.rst
  asdf/_jsonschema/exceptions.py
  asdf/_jsonschema/tests/_suite.py
  pyproject.toml
Labels: Downstream CI, jsonschema

#1817 add release date to 3.4.0 in changelog
  CHANGES.rst
Labels: no-changelog-entry-needed, Downstream CI

#1818 drop s390x, update ci
  .github/workflows/ci.yml
  .github/workflows/s390x.yml
Labels: no-changelog-entry-needed

#1797 deprecate `copy_arrays` with warning
  CHANGES.rst
  README.rst
  asdf/_asdf.py
  asdf/_tests/_regtests/test_1334.py
  asdf/_tests/_regtests/test_1525.py
  asdf/_tests/_regtests/test_1530.py
  asdf/_tests/_regtests/test_1558.py
  asdf/_tests/tags/core/tests/test_ndarray.py
  asdf/_tests/test_api.py
  asdf/_tests/test_array_blocks.py
  asdf/_tests/test_deprecated.py
  asdf/_tests/test_yaml.py
  docs/asdf/arrays.rst
Labels: Downstream CI

#1823 ignore files changed by rtd to fix version
  .readthedocs.yaml
Labels: no-changelog-entry-needed

#1824 remove non-working reference file tests
  asdf/_tests/test_reference_files.py
Labels: no-changelog-entry-needed

#1826 handle changelog entries with `towncrier`
  .github/pull_request_template.md
  .github/workflows/changelog.yml
  .readthedocs.yaml
  CHANGES.rst
  CONTRIBUTING.rst
  changes/.gitkeep
  docs/rtd_environment.yaml
  pyproject.toml
Labels: no-changelog-entry-needed

#1829 fix readthedocs build to not require user input for `towncrier build`
  .readthedocs.yaml
Labels: no-changelog-entry-needed

#1831 update change log entry types and add to pull request template
  .github/pull_request_template.md
  CONTRIBUTING.rst
  changes/1828.general.rst
  pyproject.toml
Labels: no-changelog-entry-needed

#1819 deprecate ignore_version_mismatch
  asdf/_asdf.py
  asdf/_tests/test_deprecated.py
  changes/1819.removal.rst
  pytest_asdf/plugin.py
Labels: Downstream CI
