Repository asdf-format/asdf, pull requests merged in 2024-07, with the labels that each got.

#1794 get tags for rtd
  .readthedocs.yaml
Labels: no-changelog-entry-needed

#1796 update changelog for 3.3.0 release
  CHANGES.rst
Labels: no-changelog-entry-needed, Downstream CI

#1802 consolidate build workflow
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: no-changelog-entry-needed

#1805 require pytest 8 to deal with warnings change
  pyproject.toml
Labels: no-changelog-entry-needed

#1809 improve error when an object fails to serialize
  CHANGES.rst
  asdf/_tests/test_extension.py
  asdf/_tests/test_yaml.py
  asdf/exceptions.py
  asdf/yamlutil.py
  docs/conf.py
Labels: Downstream CI

#1810 DEP: drop importlib_metadata as a dependency on Python 3.12 and newer
  CHANGES.rst
  asdf/_entry_points.py
  asdf/_tests/test_entry_points.py
  asdf/util.py
  docs/conf.py
  pyproject.toml
Labels: Downstream CI
