Repository asdf-format/asdf, pull requests merged in 2024-10, with the labels that each got.

#1843 update changelog for 3.5.0
  CHANGES.rst
  changes/1819.removal.rst
  changes/1825.bugfix.rst
  changes/1827.doc.rst
  changes/1828.general.rst
  changes/1830.doc.rst
Labels: no-changelog-entry-needed, Downstream CI

#1846 use non-dev python 3.13
  .github/workflows/ci.yml
Labels: no-changelog-entry-needed

#1845 add abacusutils to downstream
  .github/workflows/downstream.yml
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI

#1851 change atomic file prefix
  asdf/_extern/atomicfile.py
Labels: no-changelog-entry-needed

#1854 improve pull request template checklist
  .github/pull_request_template.md
Labels: no-changelog-entry-needed

#1853 Error for Convert subclasses with multiple tags if select_tag isn't implemented
  asdf/_tests/test_extension.py
  asdf/extension/_converter.py
  changes/1853.feature.rst
Labels: Downstream CI
