Repository asdf-format/asdf, pull requests merged in 2025-01, with the labels that each got.

#1875 improve schema info collection combiner handling
  asdf/_asdf.py
  asdf/_node_info.py
  asdf/_tests/test_info.py
  changes/1875.bugfix.rst
Labels: Downstream CI

#1894 pyproject.toml: version_file requires setuptools_scm>=8
  pyproject.toml
Labels: no-changelog-entry-needed

#1896 fix dkist downstream test
  tox.ini
Labels: no-changelog-entry-needed, Downstream CI

#1898 prep 4.1.0 release notes
  CHANGES.rst
  changes/1875.bugfix.rst
  changes/1880.doc.rst
  changes/1884.bugfix.0.rst
  changes/1884.bugfix.1.rst
  changes/1884.bugfix.2.rst
  changes/1884.bugfix.3.rst
  changes/1884.feature.rst
  changes/1897.doc.rst
Labels: no-changelog-entry-needed, Downstream CI
